app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), unique=True, index=True)
    username = db.Column(db.String(64), unique=True, index=True)
    password_hash = db.Column(db.String(128))
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))
    about_me = db.Column(db.Text())
    posts = db.relationship('Post', backref='author', lazy='dynamic')
    comments = db.relationship('Comment', backref='author', lazy='dynamic')

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.password_hash,password)

    # def __init__(self, **kwargs):
    #     super(User, self).__init__(**kwargs)
    #     if self.role is None:
    #         if self.email == current_app.config['BLOG_ADMIN']:
    #             self.role = Role.query.filter_by(permissions=0xff).first()
    #         if self.role is None:
    #             self.role = Role.query.filter_by(default=True).first()

    # def can(self, permissions):
    #     return self.role is not None and \
    #         (self.role.permissions & permissions) == permissions

    # def is_administrator(self):
    #     return self.can(Permission.ADMINISTER)

    def __repr__(self):
        return f'User {self.username}' 

class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    default = db.Column(db.Boolean, default=False, index=True)
    permissions = db.Column(db.Integer)
    users = db.relationship('User', backref='role', lazy='dynamic')

    @staticmethod
    def insert_roles():
        roles = {
            'User': (Permission.FOLLOW |
                     Permission.COMMENT |
                     Permission.WRITE_ARTICLES, True),
            'Moderator': (Permission.FOLLOW |
                          Permission.COMMENT |
                          Permission.WRITE_ARTICLES |
                          Permission.MODERATE_COMMENTS, False),
            'Administrator': (0xff, False)
        }
        for r in roles:
            role = Role.query.filter_by(name=r).first()
            if role is None:
                role = Role(name=r)
            role.permissions = roles[r][0]
            role.default = roles[r][1]
            db.session.add(role)
        db.session.commit()

    def __repr__(self):
        return f'User {self.name}'

class Permission:
    FOLLOW = 0x01
    COMMENT = 0x02
    WRITE_ARTICLES = 0x04
    MODERATE_COMMENTS = 0x08
    ADMINISTER = 0x80

class Post(db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.Text)
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    author_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    comments = db.relationship('Comment', backref='post', lazy='dynamic')

class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.Text)
    disabled = db.Column(db.Boolean)
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    author_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    post_id = db.Column(db.Integer, db.ForeignKey('posts.id'))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import Required

class ProfileForm(FlaskForm):
    about_me = TextAreaField('About me', validators = [Required()])
    submit = SubmitField('Submit')

class PostForm(FlaskForm):
    body = TextAreaField("What's on your mind?", validators=[Required()])
    submit = SubmitField('Submit')

class CommentForm(FlaskForm):
    body = StringField('', validators=[Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_moment import Moment

bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
from flask_uploads import UploadSet,configure_uploads,IMAGES

photos = UploadSet('photos',IMAGES)
def create_app(config_name):
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # configure UploadSet
    configure_uploads(app,photos)

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    moment = Moment(app)
    

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

# Adding the Permission class to the template context
# @main.app_context_processor
# def inject_permissions():
#     return dict(Permission=Permission)

app/main/views.py
from flask import render_template,request,redirect,url_for,abort,flash
from . import main
from flask_login import login_required,current_user
from ..models import User, Post, Permission, Comment
from .forms import ProfileForm,PostForm,CommentForm
from .. import db

@main.route('/', methods=['GET', 'POST'])
def index():
    post_form = PostForm()
    if post_form.validate_on_submit():
        post = Post(body=post_form.body.data,author=current_user._get_current_object())
        db.session.add(post)
        return redirect(url_for('.index'))
    posts = Post.query.order_by(Post.timestamp.desc()).all()
    return render_template('index.html', post_form=post_form, posts=posts)

@main.route('/user/<username>')
def user(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        abort(404)
    posts = user.posts.order_by(Post.timestamp.desc()).all()
    return render_template('user.html', user=user, posts=posts)

@main.route('/edit-profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    profile_form = ProfileForm()
    if profile_form.validate_on_submit():
        current_user.about_me = profile_form.about_me.data 
        db.session.add(user)
        db.session.commit()
        flash('Your Profile has been updated.')
        return redirect(url_for('.user', username=current_user.username))
    profile_form.about_me.data = current_user.about_me
    return render_template('edit_profile.html', profile_form=profile_form)

@main.route('/post/<int:id>', methods=['GET', 'POST'])
def post(id):
    post = Post.query.get_or_404(id)
    comment_form = CommentForm()
    if comment_form.validate_on_submit():
        comment = Comment(body=comment_form.body.data,
                          post=post)
        db.session.add(comment)
        db.session.commit()
        flash('Your comment has been published.', 'success')
        return redirect(url_for('.index', id=post.id))
    return render_template('comment.html', post=post, comment_form=comment_form)

@main.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id):
    post = Post.query.get_or_404(id)
    if current_user != post.author:
       abort(403)
    post_form = PostForm()
    if post_form.validate_on_submit():
        post.body = post_form.body.data
        db.session.add(post)
        flash('The post has been updated.')
        return redirect(url_for('.user', username=current_user.username))
    post_form.body.data = post.body
    return render_template('edit_post.html', post_form=post_form)

@main.route('/edit/<int:id>/delete', methods=['POST'])
@login_required
def delete_post(id):
    post = Post.query.get_or_404(id)
    if current_user != post.author:
       abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('.user', username=current_user.username))

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %} The Blog {% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">The Blog</a>
        </div>
       <div class="navbar-collapse collapse">
           <ul class="nav navbar-nav">
               <li><a href="/">Home</a></li>
           </ul>
           <ul class="nav navbar-nav navbar-right">
               {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('main.user', username=current_user.username) }}">Profile</a></li>
               {% endif %}
               {% if current_user.is_authenticated %}
               <li><a href="{{url_for('auth.logout')}}">Sign Out</a></li>
               {% else %}
               <li><a href="{{url_for('auth.login')}}">Sign In</a></li>
               {% endif %}
           </ul>
       </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% block page_content %}{% endblock %}
</div>
{% endblock %}

app/templates/comment.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf%}

{% block title %}The Blog - Comment{% endblock %}

{% block page_content %}
<div class="page-header">
    <div class="col-md-4">
        <h3>Write your comment.</h3>
        {{ wtf.quick_form(comment_form) }}
    </div> 
</div>

{% endblock %}

app/templates/edit_post.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf%}

{% block title %}The Blog - Edit Post{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Edit Post</h1>
</div>
<div>
    {{ wtf.quick_form(post_form) }}
</div>

{% endblock %}

app/templates/edit_profile.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf%}

{% block title %}The Blog - Edit Profile{% endblock %}

{% block page_content %}
<div class="page-header">
    <div class="col-md-4">
        {{ wtf.quick_form(profile_form) }}
    </div> 
</div>

{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf%}

{% block title %}Home{% endblock %}

{% block page_content %}
<div class="page-header">
    Hello,
    {% if current_user.is_authenticated %}
        {{ current_user.username }}
    {% else %}
        Stranger
    {% endif %}
</div>
<div>
    {{ wtf.quick_form(post_form) }}
</div>
<ul class="posts">
    {% for post in posts %}
    <li class="post">
    <div class="row">
        <div class="col-md-3 profile-thumbnail">
            <a href="{{ url_for('.user', username=post.author.username) }}">
                <img class="img-rounded" src="https://avatars0.githubusercontent.com/u/16845163?s=88&v=4" height="100px" width="100px">
            </a>
        </div>
        <div class="post-date">{{ moment(post.timestamp).fromNow() }}</div>
        <div class="col-md-9 post-author">
            <a href="{{ url_for('.user', username=post.author.username) }}">
                {{ post.author.username }}
            </a>
        </div>
        <div class="post-body">{{ post.body }}</div>
        <a href="{{ url_for('.post', id=post.id) }}">
            <span class="label label-primary">
                {{ post.comments.count() }} Comments
            </span>
        </a>
    </div>
    </li>
    {% endfor %}
</ul>
{% endblock %}

app/templates/posts.html
    {% for post in posts %}
<div class="container mx-2px">
    <div class="row">
        <div class="col-sm-4 profile-thumbnail">
            <a href="{{ url_for('.user', username=post.author.username) }}">
                <img class="mx-2px" src="https://avatars0.githubusercontent.com/u/16845163?s=88&v=4" height="100px" width="100px">
            </a>
        </div>
        <div class="col-sm-8 post-author">
            <a href="{{ url_for('.user', username=post.author.username) }}">
                {{ post.author.username }}
            </a>
        </div>
        <div class="post-body">{{ post.body }}</div>
        {% if current_user == post.author %}
        <div>
        <a class="btn btn-primary btn-sm m-1" href="{{ url_for('.edit', id=post.id) }}">Edit</a>
        <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
        </div>
        {% endif %}
    </div> 
</div>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('.delete_post', id=post.id) }}" method="POST">
              <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endfor %}

app/templates/user.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block page_content %}
<div class="container">
    <div class="page-header">
        <h1> {{ user.username|capitalize }}</h1>

        <!--Display user about_me-->
        {% if user.about_me %}
            <p>{{ user.about.me }}</p>
        {% else %}
            <p> {{ user.username|capitalize }} has no about me</p>
        {% endif %}

        <!--Profile editing link-->
        {% if user == current_user %}
        <a class="btn btn-default" href="{{ url_for('.edit_profile') }}"> Edit Profile</a>
        {% endif %}
        <h3>Posts by {{ user.username }}</h3>
        {% include 'posts.html' %}
    </div>
</div>

{% endblock %}